language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.6

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements_test.txt

script: python tests.py
