language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.15
  - DJANGO_VERSION=1.9.10
  - DJANGO_VERSION=1.10.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements_test.txt

script: python tests.py
